name: generate animation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # Debugging the repository owner name (to confirm if it's the organization or user)
      - name: Debug Repository Owner
        run: echo "Repository Owner: ${{ github.repository_owner }}"

      # Generates a snake game from a GitHub user’s contributions graph
      - name: Generate GitHub Contribution Grid Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: 'individual_username'  # Replace with the specific GitHub username
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Push the generated SVG animation to the output branch
      - name: Push GitHub Contribution Snake SVG to Output Branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
